# Introduction to R
## Basic Commands

```{r}
x =c(1,6,2)
x
```

```{r}
y=c(1,4,3)
y
```
```{r}
length(x)
```
```{r}
length(y)
```

```{r}
x+y
```

```{r}
ls()
```
```{r}
rm(x,y)
```

```{r}
ls()
```

```{r}
rm(list=ls())
```

```{r}
?matrix
```

```{r}
x=matrix(data=c(1,2,3,4),nrow=2,ncol=2)
x
```

```{r}
matrix(c(1,2,3,4),2,2)
```

```{r}
matrix(c(1,2,3,4),2,2,byrow=TRUE)
```

```{r}
sqrt(x)
```

```{r}
x^2
```

```{r}
x=rnorm(50)
x
```
```{r}
y=x+rnorm(50, mean=50, sd=1)
y
```

```{r}
cor(x,y)
```

```{r}
set.seed(1729)
rnorm(50)
```

```{r}
set.seed(1729)
y=rnorm(100)
y
```

```{r}
mean(y)
```
```{r}
var(y)
```
```{r}
sqrt(var(y))
```
```{r}
sd(y)
```


## Graphics

```{r}
x=rnorm(50)
y=rnorm(50)
plot(x,y)
```

```{r}
x=rnorm(50)
y=rnorm(50)
plot(x,y,
     xlab='X-axis',
     ylab='Y-axis',
     main='Plot X vs Y')
```

```{r}
x=rnorm(50)
y=rnorm(50)
plot(x,y,
     xlab='X-axis',
     ylab='Y-axis',
     main='Plot X vs Y')
pdf("Figure.pdf")
```

```{r}
plot(x,y,col='green')
```

```{r}
plot(x,y,col='green')

dev.off()
```

```{r}
x=seq(1,10)
x
```

```{r}
x=1:10
x
```

```{r}
x=seq(-pi,pi,length=50)
x
```

```{r}
y=-x
f=outer(x,y,function(x,y) cos(y)/(1+x^2))
contour(x,y,f)
contour(x,y,f, nlevels=45, add=T)
fa=(f-t(f))/2
contour(x,y,fa,nlevels = 15)
```

```{r}
image(x,y,fa)
```

## Indexing Data

```{r}
A=matrix(1:16,4,4)
A
```

```{r}
A[2,3]
```

```{r}
A[c(1,3),c(2,4)]
```

```{r}
A[1:3,2:4]
```

```{r}
A[1:2,]
```

```{r}
A[,1:2]
```

```{r}
A[1,]
```

```{r}
A[-c(1,3),]
```

```{r}
A[-c(1,3),-c(1,3,4)]
```

```{r}
dim(A)
```

## Loading Data

```{r}
Auto=read.table("Auto.data")
```

```{r}
View(Auto)
```

```{r}
head(Auto)
```

```{r}
Auto=read.table("Auto.data",header=T,na.strings="?",stringsAsFactors = T)
View(Auto)
```

```{r}
Auto=read.table("Auto.data",na.strings="?",stringsAsFactors = T)
View(Auto)
```

```{r}
dim(Auto)
```

```{r}
Auto=na.omit(Auto)
dim(Auto)
```

```{r}
names(Auto)
```

## Additional Graphical and Numerical Summaries

```{r}
plot(cylinders,mpg)
```
```{r}
plot(Auto$cylinders,Auto$mpg)
```

```{r}
attach(Auto)
plot(cylinders,mpg)
```

```{r}
cylinders=as.factor(cylinders)
```

```{r}
plot(cylinders,mpg)
```

```{r}
plot(cylinders,mpg, col='red')
```

```{r}
plot(cylinders,mpg,col='red',varwidth=T)
```

```{r}
plot(cylinders,mpg,col='red',varwidth=T,horizontal=T)
```

```{r}
plot(cylinders,mpg,col='red',varwidth=T,
     xlab='cylinders',
     ylab='MPG')

```

```{r}
hist(mpg)
```

```{r}
hist(mpg,col=2)
```

```{r}
hist(mpg,col=2,breaks=15)
```

```{r}
pairs(Auto)
```

```{r}
pairs(
  ~mpg+displacement+horsepower+weight+acceleration, data=Auto
)
```

```{r}
plot(horsepower,mpg)
```

```{r}
plot(horsepower,mpg)
indentify(horsepower,mpg,name)
```

```{r}
summary(Auto)
```


```{r}
summary(mpg)
```














