---
---
---

# Linear Regression Demonstration

## Libraries

```{r}
library(MASS)
```

```{r}
library(ISLR2)
```

```{r}
install.packages("MASS")
```

```{r}
install.packages("ISLR2")
```

```{r}
library(MASS)
library(ISLR2)
```

## Simple Linear Regression

```{r}
?Boston
```

```{r}
lm.fit=lm(medv~lstat)
```

```{r}
lm.fit=lm(medv~lstat,data=Boston)

```

```{r}
attach(Boston)
lm.fit=lm(medv~lstat)
```

```{r}
lm.fit
```

```{r}
summary(lm.fit)
```

```{r}
names(lm.fit)
```

```{r}
lm.fit$coefficients
```

```{r}
coef(lm.fit)
```

```{r}
confint(lm.fit)
```

```{r}
predict(lm.fit, data.frame(lstat=(c(5,10,15))), interval = "confidence")
```

```{r}
predict(lm.fit, data.frame(lstat=(c(5,0,15))),interval="prediction")
```

```{r}
plot(lstat,medv)
abline(lm.fit)
```

```{r}
abline(lm.fit,lwd=3)
abline(lm.fit, lwd=3,  col='red')
plot(lstat,medv,col='red')
plot(lstat,medv,pch=20)
plot(lstat,medv,pch="+")
plot(1:20,1:20,pch=1:20)
```

```{r}
par(mfrow=c(2,2))
plot(lm.fit)
```

```{r}
plot(predict(lm.fit),residuals(lm.fit))
plot(predict(lm.fit),rstudent(lm.fit))
```

```{r}
plot(hatvalues(lm.fit))
which.max(hatvalues(lm.fit))
```

## Multiple Linear Regression

```{r}
lm.fit=lm(medv~lstat+age, data=Boston)
summary(lm.fit)
```

```{r}
lm.fit=lm(medv~.,data=Boston)
summary(lm.fit)
```

```{r}
?summary.lm
```

```{r}
summary(lm.fit)$r.sq
```

```{r}
summary(lm.fit)$sigma
```

```{r}
install.packages("car")
```

```{r}
library(car)
```

```{r}
vif(lm.fit)
```

```{r}
lm.fit1=lm(medv~.-age,data=Boston)
summary(lm.fit1)
```

```{r}
lm.fit1=update(lm.fit,~.-age)
```

## Interaction Terms

```{r}
summary(lm(medv~lstat*age,data=Boston))
```

## Non-Linear Transformation of Predictors

```{r}
lm.fit2=lm(medv~lstat+I(lstat^2))
summary(lm.fit2)
```

```{r}
lm.fit=lm(medv~lstat)
anova(lm.fit,lm.fit2)
```

```{r}
par(mfrow=c(2,2))
plot(lm.fit2)
```

```{r}
lm.fit5=lm(medv~poly(lstat,5))
summary(lm.fit5)
```

```{r}
summary(lm(medv~log(rm),data=Boston))
```

## Qualitative Predictors

```{r}
head(Carseats)
```

```{r}
lm.fit=lm(Sales~. +Income:Advertising + Price:Age, data=Carseats)
summary(lm.fit)
```

```{r}
attach(Carseats)
contrasts(ShelveLoc)
```

```{r}
?contrasts
```

## Writing Functions

```{r}
LoadLibraries
```

```{r}
LoadLibraries()
```

```{r}
LoadLibraries=function(){
  library(ISLR2)
  library(MASS)
  print("The libraries have been loaded")
}
```

```{r}
LoadLibraries
```

```{r}
LoadLibraries()
```
